 DROP DATABASE IF EXISTS ttschool;
 CREATE DATABASE ttschool;
 USE  ttschool;

 CREATE TABLE trainee (
id INT(10) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
rating int (1),
 PRIMARY KEY (id)
)
 ENGINE=INNODB DEFAULT CHARSET=utf8;

 CREATE TABLE subject (
id INT(10) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

 CREATE TABLE groupe(
id INT(10) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
room int(1)  NOT NULL,
schoolid INT(1) NOT NULL,
  PRIMARY KEY (id)
)
 ENGINE=INNODB DEFAULT CHARSET=utf8;


 CREATE TABLE school(
id INT(10) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
year int(1)  NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;